### ISSUE TITLE
92 : HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 2)

### ISSUE THREAD

**Issue by namakr655** [datamweb/shield-oauth#1]
After successfully authenticating Google account, when I reach "https://localhost:8000/oauth/call-back" I get this error:

**CodeIgniter\HTTP\Exceptions\HTTPException**
**_92 : HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 2)_**

I am not facing any such issue with Github authentication. It is only with Google.

![ci4-oauth-http-error](https://user-images.githubusercontent.com/91448730/199546340-1ffdc691-97b9-4da6-940b-ba1cdb16b671.JPG)

**Comment by datamweb** [comment]
Hi, 
Do you use `https` in localhost?
Is this problem solved by changing the callback address to `http://localhost:8000/oauth/call-back` in the Google console?

**Comment by namakr655** [comment]
> Hi, Do you use `https` in localhost?

Yes I'm using https in localhost.

So should I change it to http at both places (Google console as well as local server) or only at Google console?

**Comment by datamweb** [comment]
Please change in both and check if your error was resolved?

**Comment by namakr655** [comment]
Still now working. Used http at both places.

I have googled a bit and many seem to suggest to use HTTP/1.1.

**Comment by datamweb** [comment]
@namakr655  Unfortunately, I cannot reproduce your error.
You can add `'version' => 1.1,` below for change.
https://github.com/datamweb/shield-oauth/blob/c070ea1c707fa70dc3e9dba319696da86a24ea9b/src/Libraries/GoogleOAuth.php#L80

If not ok, please provide more details so I can reproduce the error.

**Comment by namakr655** [comment]
Now it is working. I set the version to 1.1.

It's really strange as I cannot really understand the reason why it would not work with 2.0.

**Comment by datamweb** [comment]
**2.0 is currently unsupported.**  More info [see](https://codeigniter4.github.io/userguide/libraries/curlrequest.html#version)

**Comment by namakr655** [comment]
Thanks for help 👍
