### ISSUE TITLE
Bug: Cannot declare class Config\ShieldOAuthConfig, because the name is already in use

### ISSUE THREAD

**Issue by nicojmb** [datamweb/shield-oauth#120]
### PHP Version

8.3.8

### CodeIgniter4 Version

4.5.3

### Shield Version

	v1.1.0

### Shield OAuth Version?

dev-develop

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

 MariaDB 10.5.24

### Did you add customize OAuth?

No

### What happened?

Cannot declare class Config\ShieldOAuthConfig, because the name is already in use

### Steps to Reproduce

Upgrade to latest CI4 4.5.3 and add this to composer.json (this is suggested by upgrade guide)

```
"psr-4": {
            "App\\": "app/",
            "Config\\": "app/Config"
        },
```

### Expected Output

not show the redeclare error.

### Anything else?

if remove this psr-4, all works fine.

**Comment by datamweb** [comment]
@nicojmb ,Thank you for your report.

I installed CI4.5.3 + Shield 1.1.0 and shield-oauth dev-develop. My **composer.json** is as follows:

```json
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Config\\": "app/Config"
        },
        "exclude-from-classmap": [
            "**/Database/Migrations/**"
        ]
    },
```
But unfortunately I could not reproduce your problem.

Please make sure that changes [PR 8745](https://github.com/codeigniter4/CodeIgniter4/pull/8745) are applied to your project. If the code is updated, Please provide more details to reproduce this problem.

**Comment by nicojmb** [comment]
Sorry for the delay, the error occurs with the custom library "MicrosoftOAuth.php".

I fixed there.

**Comment by datamweb** [comment]
Thanks for the reply.
