### ISSUE TITLE
Dev: CLI `make:oauth` To quickly build other OAuth

### ISSUE THREAD

**Issue by datamweb** [datamweb/shield-oauth#3]
Command ```php spark  make:oauth newOAuth``` allows the user to perform all the steps described in [add-new-oauth-to-shield-oauth ](https://github.com/datamweb/shield-oauth/blob/main/docs/add_other_oauth.md#add-new-oauth-to-shield-oauth) through the terminal.

**Comment by sammyskills** [comment]
Hi @datamweb, 

Thank you for the effort put to create this library.

If this issue is not already in-the-works, please assign it to me so I can start working on it.

Cheers.

**Comment by datamweb** [comment]
Hey @sammyskills, welcome.

I will be happy if you do it.🫣
