### ISSUE TITLE
92 : HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2) 

### ISSUE THREAD

**Issue by luciocodeigniter** [datamweb/shield-oauth#43]
### PHP Version

8.2.5

### CodeIgniter4 Version

4.3.6

### Shield Version

beta

### Shield OAuth Version?

dev-main

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

5.7.33

### Did you add customize OAuth?

NO

### What happened?

I'm trying to use google oauth and I got the error:

92 : HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2) 

![image](https://github.com/datamweb/shield-oauth/assets/100212803/4b163bb8-cd19-4c69-b107-16e5b7d7c74c)

### Steps to Reproduce

I tried using Google's login button

### Expected Output

working

**Comment by datamweb** [comment]
Hi, first of all please use **develop** branch:
```console
composer require datamweb/shield-oauth:dev-develop
```

Use the method described below to fix the error:

https://github.com/datamweb/shield-oauth/issues/1#issuecomment-1303157306

**Comment by luciocodeigniter** [comment]
Thanks for the quick response. It worked out.

**Comment by luciocodeigniter** [comment]
Thanks for the quick response. It worked out.
