### ISSUE TITLE
Bug: ShieldOAuthModel not initializing parent

### ISSUE THREAD

**Issue by clsmedia** [datamweb/shield-oauth#56]
### PHP Version

8.1.23

### CodeIgniter4 Version

4.4.1

### Shield Version

dev-develop

### Shield OAuth Version?

dev-main

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

mysql:latest

### Did you add customize OAuth?

no, just Google

### What happened?

On oauth/call-back i got an error: 
Typed property CodeIgniter\Shield\Models\BaseModel::$tables must not be accessed before initialization
VENDORPATH/codeigniter4/shield/src/Models/UserModel.php at line 196

194         if ($email !== null) {
195             $data = $this->select(
196                 sprintf('%1$s.*, %2$s.secret as email, %2$s.secret2 as password_hash', $this->table, $this->tables['identities'])
197             )

i think thats because $this->tables is null which - i believe - is because we're not initializing parent in ShieldOAuthModel

### Steps to Reproduce

just regular setup according to repo guide

### Expected Output

one should be logged in (or not)

**Comment by datamweb** [comment]
Thanks for your report.

Please use branch develop.
```console
composer require datamweb/shield-oauth:dev-develop
```

**Comment by clsmedia** [comment]
Thanks!
